---
- name: Install the packages
  hosts: 127.0.0.1
  become: yes  # Gain root privileges to install the packages

  vars_files:
    - variables.yml

  tasks:
    - name: Clean yum cache
      ansible.builtin.command: yum clean all

    - name: Update the package index
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes  # Ensure the cache is updated

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - nano
          - git
          - htop
          - curl
          - telnet
          - yum-utils
          - net-tools
          - bind-utils
          - iptables
          - device-mapper-persistent-data
          - lvm2
          - mlocate
          - docker-ce
          - python3-pip
          - certbot
          - certbot-nginx
        state: latest

    - block:
        - name: Download Docker Compose
          ansible.builtin.command: >
            curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}" -o "{{ docker_compose_exe_location }}"
          args:
            creates: "{{ docker_compose_exe_location }}"

        - name: Make Docker Compose executable
          ansible.builtin.command: chmod +x "{{ docker_compose_exe_location }}"
      when: ansible_os_family == "Linux"
