---
- name: Install the packages
  hosts: all
  become: yes  # Gain root privileges to install the packages
  tasks:
    - name: Clean yum cache
      ansible.builtin.command: yum clean all

    - name: Update the package index
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes  # Ensure the cache is updated

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - nano
          - git
          - htop
          - curl
          - telnet
          - yum-utils
          - net-tools
          - bind-utils
          - iptables
          - device-mapper-persistent-data
          - lvm2
          - mlocate
          - docker-ce
          - python3-pip
        state: latest

    - block:
        - name: Download Docker Compose
          ansible.builtin.command: >
            curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}" -o /usr/local/bin/docker-compose
          args:
            creates: /usr/local/bin/docker-compose  # Only run if the file does not exist

        - name: Make Docker Compose executable
          ansible.builtin.command: chmod +x /usr/local/bin/docker-compose
      when: ansible_os_family == "Linux"
